### ISSUE TITLE
 `pinch': undefined method `to_point' for 5.0:Float (NoMethodError)

### ISSUE THREAD

**Issue by ericcastro** [AXElements/mouse#10]
I am also getting this error, when trying to trigger a pinch gesture

**Comment by ferrous26** [comment]
It looks like you passed a float for the third argument, but the documentation states that it takes a CGPoint or something that responds to `#to_point`. Here are some examples:

```ruby
Mouse.pinch :zoom, 5.0
Mouse.pinch :zoom, 2.0, [10.0, 100]
Mouse.pinch :unzoom, 1.0, CGPoint.new(500, 500)
```
